# Generated by Django 5.2.13 on 2026-04-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hireitem',
            name='price_per_period',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
