# Generated by Django 5.2.13 on 2026-04-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_hireitem_price_per_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hireitem',
            name='price_per_day',
        ),
        migrations.RemoveField(
            model_name='hireitem',
            name='price_per_period',
        ),
        migrations.AddField(
            model_name='hireitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base price', max_digits=10),
        ),
        migrations.AddField(
            model_name='hireitem',
            name='pricing_type',
            field=models.CharField(choices=[('period', 'Per Hire Period (Thu-Mon)'), ('day', 'Per Day'), ('week', 'Per Week')], default='period', help_text='How this item is priced', max_length=10),
        ),
    ]
